runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$
- .git
- log/*
- frontend/node_modules
- frontend/.cache
- backup


handlers:

- url: /static
  static_dir: frontend/build/static

- url: /.*
  script: main.app

